apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: microsoftsentinelanalyticrules.buildrlabs.io
spec:
  group: buildrlabs.io
  names:
    categories: []
    kind: MicrosoftSentinelAnalyticRule
    plural: microsoftsentinelanalyticrules
    shortNames:
    - msanalytic
    - msanalytics
    - msanalyticrule
    - msanalyticrules
    singular: microsoftsentinelanalyticrule
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Checks if the Detection Rule is deployed to Microsoft Sentinel
      jsonPath: .status.create_analytic_rule.deployed
      name: Status
      type: string
    - description: Checks if the Detection Rule is enabled in Microsoft Sentinel
      jsonPath: .status.create_analytic_rule.enabled
      name: Enabled
      type: string
    - description: Additional information about the deployment status
      jsonPath: .status.create_analytic_rule.message
      name: Message
      type: string
    - description: The type of Microsoft Sentinel Detection Rule
      jsonPath: .status.create_analytic_rule.rule_type
      name: Rule type
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for MicrosoftSentinelAnalyticRuleSpec via `CustomResource`
        properties:
          spec:
            properties:
              kind:
                default: Scheduled
                type: string
              properties:
                properties:
                  alertDetailsOverride:
                    nullable: true
                    properties:
                      alertDescriptionFormat:
                        nullable: true
                        type: string
                      alertDisplayNameFormat:
                        nullable: true
                        type: string
                      alertSeverityColumnName:
                        nullable: true
                        type: string
                      alertTacticsColumnName:
                        nullable: true
                        type: string
                    type: object
                  alertRuleTemplateName:
                    nullable: true
                    type: string
                  customDetails:
                    additionalProperties: true
                    nullable: true
                    type: object
                  description:
                    nullable: true
                    type: string
                  displayName:
                    type: string
                  enabled:
                    type: boolean
                  entityMappings:
                    items:
                      properties:
                        entityType:
                          enum:
                          - Account
                          - AzureResource
                          - CloudApplication
                          - DNS
                          - File
                          - FileHash
                          - Host
                          - IP
                          - MailCluster
                          - MailMessage
                          - Mailbox
                          - Malware
                          - Process
                          - RegistryKey
                          - RegistryValue
                          - SecurityGroup
                          - SubmissionMail
                          - URL
                          type: string
                        fieldMappings:
                          items:
                            properties:
                              columnName:
                                type: string
                              identifier:
                                type: string
                            required:
                            - columnName
                            - identifier
                            type: object
                          type: array
                      required:
                      - entityType
                      - fieldMappings
                      type: object
                    nullable: true
                    type: array
                  eventGroupingSettings:
                    nullable: true
                    properties:
                      aggregationKind:
                        enum:
                        - AlertPerResult
                        - SingleAlert
                        type: string
                    required:
                    - aggregationKind
                    type: object
                  incidentConfiguration:
                    nullable: true
                    properties:
                      createIncident:
                        type: boolean
                      groupingConfiguration:
                        properties:
                          enabled:
                            type: boolean
                          groupByAlertDetails:
                            items:
                              properties:
                                displayName:
                                  type: string
                                severity:
                                  enum:
                                  - High
                                  - Informational
                                  - Low
                                  - Medium
                                  type: string
                              required:
                              - displayName
                              - severity
                              type: object
                            type: array
                          groupByCustomDetails:
                            items:
                              type: string
                            type: array
                          groupByEntities:
                            items:
                              enum:
                              - Account
                              - AzureResource
                              - CloudApplication
                              - DNS
                              - File
                              - FileHash
                              - Host
                              - IP
                              - MailCluster
                              - MailMessage
                              - Mailbox
                              - Malware
                              - Process
                              - RegistryKey
                              - RegistryValue
                              - SecurityGroup
                              - SubmissionMail
                              - URL
                              type: string
                            type: array
                          lookbackDuration:
                            type: string
                          matchingMethod:
                            enum:
                            - AllEntities
                            - AnyAlert
                            - Selected
                            type: string
                          reopenClosedIncident:
                            type: boolean
                        required:
                        - enabled
                        - groupByAlertDetails
                        - groupByCustomDetails
                        - groupByEntities
                        - lookbackDuration
                        - matchingMethod
                        - reopenClosedIncident
                        type: object
                    required:
                    - createIncident
                    - groupingConfiguration
                    type: object
                  query:
                    type: string
                  queryFrequency:
                    type: string
                  queryPeriod:
                    type: string
                  severity:
                    enum:
                    - High
                    - Informational
                    - Low
                    - Medium
                    type: string
                  suppressionDuration:
                    type: string
                  suppressionEnabled:
                    type: boolean
                  tactics:
                    items:
                      enum:
                      - Collection
                      - CommandAndControl
                      - CredentialAccess
                      - DefenseEvasion
                      - Discovery
                      - Execution
                      - Exfiltration
                      - Impact
                      - ImpairProcessControl
                      - InhibitResponseFunction
                      - InitialAccess
                      - LateralMovement
                      - Persistence
                      - PreAttack
                      - PrivilegeEscalation
                      - Reconnaissance
                      - ResourceDevelopment
                      type: string
                    nullable: true
                    type: array
                  techniques:
                    items:
                      type: string
                    nullable: true
                    type: array
                  templateVersion:
                    nullable: true
                    type: string
                  triggerOperator:
                    enum:
                    - Equal
                    - GreaterThan
                    - LessThan
                    - NotEqual
                    type: string
                  triggerThreshold:
                    format: int64
                    type: integer
                required:
                - displayName
                - enabled
                - query
                - queryFrequency
                - queryPeriod
                - severity
                - suppressionDuration
                - suppressionEnabled
                - triggerOperator
                - triggerThreshold
                type: object
            required:
            - properties
            type: object
          status:
            nullable: true
            properties:
              create_analytic_rule:
                properties:
                  deployed:
                    type: string
                  enabled:
                    type: string
                  message:
                    type: string
                  rule_type:
                    type: string
                required:
                - deployed
                - enabled
                - message
                - rule_type
                type: object
            required:
            - create_analytic_rule
            type: object
        required:
        - spec
        title: MicrosoftSentinelAnalyticRule
        type: object
    served: true
    storage: true
    subresources:
      status: {}
