apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: root-ca
  subject:
    organizations:
      - Buildr Labs
  secretName: root-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-ca-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: root-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admission-webhook
spec:
  secretName: admission-webhook-tls
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
    - "{{ .Values.operator.name }}.{{ .Release.Namespace }}.svc.cluster.local"
    - "{{ .Values.operator.name }}.{{ .Release.Namespace }}.svc"
    - "{{ .Values.operator.name }}"
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer