apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.operator.name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: {{ .Values.operator.name }}
  template:
    metadata:
      labels:
        application: {{ .Values.operator.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: dac-operator
        protocol: TCP
        imagePullPolicy: Always
        image: buildrlabs/dac-operator
        command: ["kopf", "run", "/operator/dac_operator/operator.py"]
        volumeMounts:
          - readOnly: true
            mountPath: /certs
            name: webhook-certs
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-webhook-tls
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.operator.name }}
spec:
  selector:
    application: {{ .Values.operator.name }}
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
