apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validate-automation-rules
  annotations:
    cert-manager.io/inject-ca-from: dac-system/admission-webhook
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ .Values.operator.name }}
      namespace: {{ .Release.Namespace }}
      path: /validate-automation-rule
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validate-automation-rules.buildrlabs.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - buildrlabs.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - microsoftsentinelautomationrules
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30